update boarding documentation
ark-network/arkdev.info pull request #12
Opened 2024-08-30 17:52 UTC by louisinger

This update the docs according to https://github.com/ark-network/ark/pull/279

@tiero @bordalix @altafan  please review

2024-08-30 17:57 UTC, tiero requested changes

2024-08-30 17:57 UTC, tiero commented on docs/learn/boarding.md
> +The boarding transaction is a unique mechanism within the Ark protocol, leveraging taproot to enable a streamlined funding process for VTXOs (Virtual Transaction Outputs). This method allows Alice to
This piece doesn't sound helpful: what's the thing enabled by taproot? It's just 2of2 or timelock on user, could be done on segwit

2024-08-30 17:57 UTC, tiero commented on docs/learn/boarding.md
> +- **Alice exit**: Alice can unlock the funds after a timeout period of 4 weeks.
It's more like 1 year or 6 months,  not 4 weeks rather...otherwise we force users to cycle sooner than needed

2024-08-30 17:57 UTC, tiero commented on docs/learn/boarding.md
> +Once the boarding transaction is confirmed on the main chain, Alice can join the Ark by submitting the UTXO to the ASP. The ASP then includes the UTXO in the next round (as input of the round transac
I think is best to explain that funding the address is enough to join that Ark. this seems to say that user MUST cycle the VTXO to board the Ark

2024-08-30 17:57 UTC, tiero commented on docs/user/cli.md
> +ark claim
Is this true?

2024-08-30 18:03 UTC, louisinger commented on docs/learn/boarding.md
> +Once the boarding transaction is confirmed on the main chain, Alice can join the Ark by submitting the UTXO to the ASP. The ASP then includes the UTXO in the next round (as input of the round transac
You cannot "async send" the boarding UTXO, you have to claim like a pending payment in other words that's what I meant

2024-08-30 18:04 UTC, louisinger commented on docs/user/cli.md
> +ark claim
yes, password flag is mainly for testing purposes not sure it's a good practice to include it in cmds in every day use

2024-08-30 18:05 UTC, louisinger commented on docs/user/cli.md
> +ark claim
it is always optional, if not set, the CLI ask the user

2024-08-30 20:26 UTC, tiero commented on docs/learn/boarding.md
> +Once the boarding transaction is confirmed on the main chain, Alice can join the Ark by submitting the UTXO to the ASP. The ASP then includes the UTXO in the next round (as input of the round transac
No I refer to the "next round". Client can wait the end of the timelock to swap it for a real VTXO born from the tree.

2024-09-03 09:43 UTC, bordalix requested changes
Besides the request changes, imho the ASP should make public the **6 month** timeout, i.e., include it on the GetInfoResponse object.

2024-09-03 09:43 UTC, bordalix commented on docs/developers/go.md
> +log.Infof("Onchain address: %s", onboardingAddr)
```suggestion
log.Infof("Onboarding address: %s", onboardingAddr)
```

2024-09-03 09:43 UTC, bordalix commented on docs/user/cli.md
> +Display your onboarding address and offchain receiving addresses:
```suggestion
Display your onboarding and offchain receiving addresses:
```

2024-09-03 09:46 UTC, louisinger commented
> Besides the request changes, imho the ASP should make public the **6 month** timeout, i.e., include it on the GetInfoResponse object.

#279 latest PR includes a boarding_descriptor_template field containing the boarding timeout. I'll update doc ASAP

2024-09-04 17:07 UTC, bordalix approved these changes

2024-09-04 17:32 UTC, tiero commented
Hold on from merging until we tag the next releases, i.e. `ark` v0.3 release

2024-09-04 18:39 UTC, tiero commented on docs/user/cli.md
> +### Claiming Pending Payments & Boarding UTXOs
Why the claim interacts with baording utxos?

2024-09-27 09:48 UTC, merged