v4 Blogpost
ark-network/arkdev.info pull request #24
Opened 2024-11-20 02:34 UTC by altafan

This is a first version of the blogpost for the upcoming Ark v4.

Please @tierp review.

2024-11-20 02:36 UTC, altafan commented
can't see why the preview build is failing

2024-11-20 13:48 UTC, tiero commented on blog/2024-11-20-release-v0.4.md
> +description: Release ARK v0.4, featuring new address encoding, Ark notes, no required settlement, and live transaction feed.
Redo

2024-11-20 13:48 UTC, tiero commented on blog/2024-11-20-release-v0.4.md
> +- This improvement reduces friction and increases the speed of off-chain transactions
This actually enabled you to create a "chain" of "pending" payments, enabling a form of fast and trust minimized payment protocol that don't require the Server to allocate liquidity for every request.

2024-11-20 13:48 UTC, tiero commented on blog/2024-11-20-release-v0.4.md
> +- This feature enables more responsive and dynamic applications built on Ark
This doesn't mean much

2024-11-20 13:48 UTC, tiero commented on blog/2024-11-20-release-v0.4.md
> +### 📡 Live Transaction Feed
Better to say Streaming/Notificatiions?

2024-11-20 13:48 UTC, tiero commented on blog/2024-11-20-release-v0.4.md
> +This is a mock of what an ideal Ark Server would do, ie broadcast messages for round and out of round transactions via Nostr.
What does this mean?

2024-11-20 13:48 UTC, tiero commented on blog/2024-11-20-release-v0.4.md
> +## 🛠️ ASP Improvements
Server

2024-11-20 13:48 UTC, tiero commented on blog/2024-11-20-release-v0.4.md
> +To start leveraging these exciting new features in Ark v0.4, update your installations and check out our [updated documentation](https://arkdev.info) for detailed guides on how to implement and use t
Link to the usage page for the server

2024-11-20 13:51 UTC, altafan commented on blog/2024-11-20-release-v0.4.md
> +description: Release ARK v0.4, featuring new address encoding, Ark notes, no required settlement, and live transaction feed.
i didn't get this

2024-11-20 13:55 UTC, altafan commented on blog/2024-11-20-release-v0.4.md
> +This is a mock of what an ideal Ark Server would do, ie broadcast messages for round and out of round transactions via Nostr.
wanted to say that now tx streaming is done through a Server API, while the plan is to send these messages over nostr

2024-11-20 13:56 UTC, altafan commented on blog/2024-11-20-release-v0.4.md
> +- This feature enables more responsive and dynamic applications built on Ark
ok i drop the last line

2024-11-20 14:20 UTC, tiero commented on blog/2024-11-20-release-v0.4.md
> +This is a mock of what an ideal Ark Server would do, ie broadcast messages for round and out of round transactions via Nostr.
No remove it not needed

2024-11-21 15:18 UTC, tiero requested changes

2024-11-28 18:19 UTC, tiero commented on blog/2024-11-20-release-v0.4.md
> +This change paves the way for more innovative applications and use cases within the Ark network. You can do your own experiments by interacting with our public Ark server [server_url] <!-- TODO: add
Do we want to do this?

2024-11-28 18:20 UTC, tiero commented on blog/2024-11-20-release-v0.4.md
> +This change paves the way for more innovative applications and use cases within the Ark network. You can do your own experiments by interacting with our public Ark server [server_url] <!-- TODO: add
also I would say 

```suggestion
This change paves the way for more innovative applications and use cases built on Bitcoin with the Ark Protocol.
```

2024-11-28 18:20 UTC, tiero commented on blog/2024-11-20-release-v0.4.md
> +This change will make the advantages of Market Hours more apparent to users. By concentrating transactions during specific periods and sharing the costs, participants should be able to benefit from l
```suggestion
This change will make the advantages of Market Hours more apparent to users. By concentrating transactions during specific periods and sharing the costs, participants should be able to benefit from lower fees. This should provide a clear incentive for users to take advantage of Market Hours, ultimately leading to a more efficient and cost-effective Ark for everyone involved.
```

2024-11-28 18:21 UTC, tiero commented on blog/2024-11-20-release-v0.4.md
> +We're also working on updating our VTXO tree signing scheme. This change is designed to [unlock liquidity before shared output expiration](https://arkdev.info/blog/unlock-liquidity-before-shared-outp
```suggestion
We're also working on updating our VTXO tree signing scheme. This change is designed to [unlock liquidity before shared output expiration](https://arkdev.info/blog/unlock-liquidity-before-shared-output-expiration), which should improve the overall sustainability of the Ark Server.
```

2024-12-05 13:09 UTC, tiero commented on blog/2024-11-20-release-v0.4.md
> +**Greetings, Arkonauts! 🚀**
```suggestion
```

2024-12-05 13:40 UTC, merged